from enum import StrEnum
from pydantic import BaseModel

class User(BaseModel):
    email: str
    hacker_id: str
    name: str
    phone: str
    paid_status: bool
    advertise_code: str = "unknown"

class NotificationType(StrEnum):
    CANDIDATE_KID_INTRO = "CANDIDATE_KID_INTRO"
    ASSIGNMENT_SUBMISSION_RESULT_PASSING_WITH_NEXT_ASSIGNMENT_LINK = "ASSIGNMENT_SUBMISSION_RESULT_PASSING_WITH_NEXT_ASSIGNMENT_LINK"
    ASSIGNMENT_SUBMISSION_RESULT_PASSING_WITHOUT_NEXT_ASSIGNMENT_LINK = "ASSIGNMENT_SUBMISSION_RESULT_PASSING_WITHOUT_NEXT_ASSIGNMENT_LINK"
    ASSIGNMENT_SUBMISSION_RESULT_FAILING_WITH_ANOTHER_ATTEMPT = "ASSIGNMENT_SUBMISSION_RESULT_FAILING_WITH_ANOTHER_ATTEMPT"
    ASSIGNMENT_SUBMISSION_RESULT_FAILING_WITHOUT_ANOTHER_ATTEMPT = "ASSIGNMENT_SUBMISSION_RESULT_FAILING_WITHOUT_ANOTHER_ATTEMPT"
    NEW_ASSIGNMENT_ARRIVED = "NEW_ASSIGNMENT_ARRIVED"
    PAYMENT_ACCEPTED = "PAYMENT_ACCEPTED"

class Notification(BaseModel):
    notification_type: NotificationType
    user: User
    send_attempt_counter: int = 0