from enum import Enum
from pydantic import BaseModel

class User(BaseModel):
    email: str
    hacker_id: str
    name: str
    phone: str
    paid_status: bool

class NotificationType(Enum):
    CANDIDATE_KID_INTRO = 1
    ASSIGNMENT_SUBMISSION_RESULT_PASSING_WITH_NEXT_ASSIGNMENT_LINK = 2
    ASSIGNMENT_SUBMISSION_RESULT_PASSING_WITHOUT_NEXT_ASSIGNMENT_LINK = 3
    ASSIGNMENT_SUBMISSION_RESULT_FAILING_WITH_ANOTHER_ATTEMPT = 4
    ASSIGNMENT_SUBMISSION_RESULT_FAILING_WITHOUT_ANOTHER_ATTEMPT = 5
    NEW_ASSIGNMENT_ARRIVED = 6